Separate affinity mask from main process
nh8157/energy-guard-v2 pull request #32
Opened 2023-08-23 22:12 UTC by Destrings2

This pull requests aims to separate the main process from the affinity mask setter. This is done because the affinity mask process requires elevated privileges, however executing the main program with them makes the notification unable to work due to User Interface Privilege Isolation.

This is done by separating the processes and using IPC through pipes to communicate between them.

2023-08-24 15:04 UTC, julesrodrigues11 approved these changes
Looks good to me!

2023-08-27 02:02 UTC, nh8157 requested changes
There seems to be an issue with measuring live power consumption. And it just occurred to me that LibreHardwareMonitor also requires admin privilege to run...
![image](https://github.com/nh8157/energy-guard-v2/assets/47706495/0281fcc0-5e8c-4160-9520-7ee761984fb8)

Also, although I can see in the CLI (verified through Task Manager) that the affinity mask has been successfully created, I still cannot see any notification showing up.

2023-09-01 16:44 UTC, icodethingz approved these changes

2023-09-04 10:47 UTC, icodethingz approved these changes

2023-09-23 14:23 UTC, icodethingz approved these changes

2023-09-24 20:30 UTC, merged